autoload -Uz colors && colors
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats " %{$fg[green]%}(%b)%{$reset_color%}"

precmd() {
    vcs_info
}

setopt prompt_subst
PROMPT='%{$fg[blue]%}[%*]%{$reset_color%} %2~${vcs_info_msg_0_} %# '

autoload -Uz compinit && compinit
autoload -Uz +X bashcompinit && bashcompinit

export HISTSIZE=100000 # default: 1000 as per zsh 5.8 on macOS
export SAVEHIST=$HISTSIZE

# Prevent contiguous duplicate history entries.
setopt HIST_IGNORE_DUPS

_dotfiles_current_shell=zsh

. $HOME/dotfiles/rc/macports

. $HOME/dotfiles/rc/android
. $HOME/dotfiles/rc/bin
. $HOME/dotfiles/rc/coreutils
. $HOME/dotfiles/rc/fnm
. $HOME/dotfiles/rc/fzf
. $HOME/dotfiles/rc/gcloud
. $HOME/dotfiles/rc/go
. $HOME/dotfiles/rc/helm
. $HOME/dotfiles/rc/istioctl
. $HOME/dotfiles/rc/java
. $HOME/dotfiles/rc/kubectl
. $HOME/dotfiles/rc/ls
. $HOME/dotfiles/rc/npm
. $HOME/dotfiles/rc/pyenv
. $HOME/dotfiles/rc/rbenv
. $HOME/dotfiles/rc/tfenv

# This should be included after PATH initialized
. $HOME/dotfiles/rc/pip

# Include WarTek bashrc	
[ -r $HOME/WarTek/dotfiles/zsh/zshrc ] && \
    . $HOME/WarTek/dotfiles/zsh/zshrc

unset _dotfiles_current_shell
