autoload -Uz colors && colors
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats " %{$fg[green]%}(%b)%{$reset_color%}"

precmd() {
    vcs_info
}

setopt prompt_subst
PROMPT='%{$fg[blue]%}[%*]%{$reset_color%} %2~${vcs_info_msg_0_} %# '

autoload -Uz compinit && compinit
autoload -Uz +X bashcompinit && bashcompinit

# Prevent contiguous duplicate history entries.
setopt HIST_IGNORE_DUPS

. $HOME/dotfiles/rc/bin
. $HOME/dotfiles/rc/coreutils
. $HOME/dotfiles/rc/go
. $HOME/dotfiles/rc/ls
. $HOME/dotfiles/rc/pyenv
. $HOME/dotfiles/rc/rbenv

# This should be included after PATH initialized
. $HOME/dotfiles/rc/pip

# Include Bukalapak zshrc
[ -r $HOME/Bukalapak/dotfiles/zsh/zshrc ] && \
    . $HOME/Bukalapak/dotfiles/zsh/zshrc
